# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Admin::User.create(name: 'Ramón Martínez Olvera', login: 'martinezo', mail: 'martinezo@inb.unam.mx')
Catalogs::State.create(name: 'Aguascalientes')
Catalogs::State.create(name: 'Baja California')
Catalogs::State.create(name: 'Baja California Sur')
Catalogs::State.create(name: 'Campeche')
Catalogs::State.create(name: 'Chiapas')
Catalogs::State.create(name: 'Chihuahua')
Catalogs::State.create(name: 'Coahuila')
Catalogs::State.create(name: 'Colima')
Catalogs::State.create(name: 'Distrito Federal')
Catalogs::State.create(name: 'Durango')
Catalogs::State.create(name: 'Guanajuato')
Catalogs::State.create(name: 'Guerrero')
Catalogs::State.create(name: 'Hidalgo')
Catalogs::State.create(name: 'Jalisco')
Catalogs::State.create(name: 'México')
Catalogs::State.create(name: 'Michoacán')
Catalogs::State.create(name: 'Morelos')
Catalogs::State.create(name: 'Nayarit')
Catalogs::State.create(name: 'Nuevo León')
Catalogs::State.create(name: 'Oaxaca')
Catalogs::State.create(name: 'Puebla')
Catalogs::State.create(name: 'Querétaro')
Catalogs::State.create(name: 'Quintana Roo')
Catalogs::State.create(name: 'San Luis Potosí')
Catalogs::State.create(name: 'Sinaloa')
Catalogs::State.create(name: 'Sonora')
Catalogs::State.create(name: 'Tabasco')
Catalogs::State.create(name: 'Tamaulipas')
Catalogs::State.create(name: 'Tlaxcala')
Catalogs::State.create(name: 'Veracruz')
Catalogs::State.create(name: 'Yucatán')
Catalogs::State.create(name: 'Zacatecas')
Catalogs::State.create(name: 'Otro')
